sudo: required
dist: trusty
language: node_js
notifications:
  email: false
addons:
  firefox: "latest"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - "6"
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get install python2.7 git-all pkg-config libncurses5-dev libssl-dev libnss3-dev libexpat-dev
  - npm config set python python2
  - sudo apt-get install libstdc++6
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get upgrade
  - sudo apt-get dist-upgrade
  - npm update -g
  - npm install -g codeclimate-test-reporter
script:
  - npm test -- karma.conf.travis.js
after_success:
  - codeclimate-test-reporter < ./coverage/lcov.info
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
